name: GitHub Actions Test
run-name: ${{ github.actor }} train ml model
on:
  push:
    branches:
        - staging
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "initiating ML model training on Azure"
      - run: echo "Checking out the repository from ${{ github.repository }}."
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: echo "Repository cloned, I think I'm ready. The files look like this:"
      - name: List files
        run: | 
          ls ${{ github.workspace }}
      - name: Log in to Azure
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Test azure login by getting details
        run: az account show
      - name: add azure ml extension
        run: az extension add --name ml
      - name: Submit job to azure
        run: az ml job create --file ./production/job.yaml --resource-group com774-cw2 --workspace-name com774-cw2
